/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#a04100",
        "on-secondary-fixed": "#001d31",
        "tertiary": "#006c4a",
        "secondary-container": "#5bb8fe",
        "on-primary-container": "#572000",
        "on-error": "#ffffff",
        "surface-container-high": "#ede7e4",
        "error-container": "#ffdad6",
        "on-background": "#1d1b19",
        "on-primary-fixed": "#351000",
        "tertiary-fixed-dim": "#68dba9",
        "secondary-fixed-dim": "#93ccff",
        "arcade-amber": "#f59e0b",
        "outline-variant": "#e2bfb0",
        "success-mint": "#10b981",
        "outline": "#8e7164",
        "tertiary-container": "#31ac7d",
        "error": "#ba1a1a",
        "surface-dim": "#ded9d5",
        "on-secondary": "#ffffff",
        "inverse-surface": "#32302e",
        "secondary-fixed": "#cce5ff",
        "tertiary-fixed": "#85f8c4",
        "inverse-primary": "#ffb693",
        "chunky-border": "#f2eae1",
        "on-primary": "#ffffff",
        "surface-tint-warm": "#fff7ed",
        "inverse-on-surface": "#f5f0ec",
        "on-error-container": "#93000a",
        "background": "#fef8f5",
        "primary": "#ff6b00",
        "secondary": "#ea580c",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f8f2ef",
        "surface-bright": "#fef8f5",
        "on-surface": "#1d1b19",
        "surface": "#fef8f5",
        "primary-fixed-dim": "#ffb693",
        "surface-container": "#f3ede9",
        "on-secondary-fixed-variant": "#004b73",
        "creative-violet": "#8b5cf6",
        "on-secondary-container": "#00476e",
        "surface-container-highest": "#e7e1de",
        "primary-fixed": "#ffdbcc",
        "on-tertiary-fixed-variant": "#005137",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#5a4136",
        "on-primary-fixed-variant": "#7a3000",
        "energy-glow": "rgba(255, 107, 0, 0.28)",
        "primary-container": "#ff6b00",
        "on-tertiary-fixed": "#002114",
        "surface-variant": "#e7e1de",
        "on-tertiary-container": "#003925"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.75rem",
        "gutter-md": "1.5rem",
        "space-xs": "0.5rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "target-min": "3.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-sm": ["Outfit", "sans-serif"],
        "body-md": ["Lexend", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-sm": ["Lexend", "sans-serif"],
        "headline-xl-mobile": ["Outfit", "sans-serif"],
        "label-lg": ["Outfit", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "title-md": ["Outfit", "sans-serif"],
        "body-lg": ["Lexend", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"]
      }
    },
  },
  plugins: [],
}
